version: '3.8'

services:
  # MongoDB for Product Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: product_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - shop_network

  # PostgreSQL for User and Order Services
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_network

  # Redis for Auth Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shop_network

volumes:
  mongodb_data:
  postgres_data:
  redis_data:

networks:
  shop_network:
    driver: bridge 